[versions]
agp                  = "9.0.1"
kotlin               = "2.0.21"
coreKtx              = "1.10.1"
junit                = "4.13.2"
junitVersion         = "1.1.5"
espressoCore         = "3.5.1"
lifecycleRuntimeKtx  = "2.8.7"
activityCompose      = "1.9.3"
composeBom           = "2025.07.00"
coroutines           = "1.10.2"
navigationCompose    = "2.8.9"
coreSplashscreen     = "1.0.1"
lottie               = "6.7.1"
firebasePerf = "22.0.4"
googleFirebaseFirebasePerf = "2.0.2"

[libraries]
# AndroidX Core
androidx-core-ktx                     = { group = "androidx.core",                    name = "core-ktx",                            version.ref = "coreKtx" }
androidx-core-splashscreen            = { group = "androidx.core",                    name = "core-splashscreen",                   version.ref = "coreSplashscreen" }

# Lifecycle
androidx-lifecycle-runtime-ktx        = { group = "androidx.lifecycle",               name = "lifecycle-runtime-ktx",               version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose  = { group = "androidx.lifecycle",               name = "lifecycle-viewmodel-compose",         version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose    = { group = "androidx.lifecycle",               name = "lifecycle-runtime-compose",           version.ref = "lifecycleRuntimeKtx" }

# Activity
androidx-activity-compose             = { group = "androidx.activity",                name = "activity-compose",                    version.ref = "activityCompose" }

# Navigation
androidx-navigation-compose           = { group = "androidx.navigation",              name = "navigation-compose",                  version.ref = "navigationCompose" }

# Compose BOM + UI
androidx-compose-bom                  = { group = "androidx.compose",                 name = "compose-bom",                         version.ref = "composeBom" }
androidx-compose-ui                   = { group = "androidx.compose.ui",              name = "ui" }
androidx-compose-ui-graphics          = { group = "androidx.compose.ui",              name = "ui-graphics" }
androidx-compose-ui-tooling           = { group = "androidx.compose.ui",              name = "ui-tooling" }
androidx-compose-ui-tooling-preview   = { group = "androidx.compose.ui",              name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest     = { group = "androidx.compose.ui",              name = "ui-test-manifest" }
androidx-compose-ui-test-junit4       = { group = "androidx.compose.ui",              name = "ui-test-junit4" }
androidx-compose-material3            = { group = "androidx.compose.material3",       name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material",    name = "material-icons-extended" }

# Firebase (versi diatur oleh BOM)
firebase-bom                          = { group = "com.google.firebase",              name = "firebase-bom",                        version = "34.9.0" }
firebase-analytics                    = { group = "com.google.firebase",              name = "firebase-analytics" }
firebase-auth-ktx                     = { group = "com.google.firebase",              name = "firebase-auth-ktx" }
firebase-firestore-ktx                = { group = "com.google.firebase",              name = "firebase-firestore-ktx" }
firebase-messaging                    = { group = "com.google.firebase",              name = "firebase-messaging" }

# Coroutines & Flow
kotlinx-coroutines-core               = { group = "org.jetbrains.kotlinx",            name = "kotlinx-coroutines-core",             version.ref = "coroutines" }
kotlinx-coroutines-android            = { group = "org.jetbrains.kotlinx",            name = "kotlinx-coroutines-android",          version.ref = "coroutines" }
kotlinx-coroutines-play-services      = { group = "org.jetbrains.kotlinx",            name = "kotlinx-coroutines-play-services",    version.ref = "coroutines" }

# Third-party
lottie                                = { group = "com.airbnb.android",               name = "lottie",                              version.ref = "lottie" }
timber                                = { group = "com.jakewharton.timber",            name = "timber",                              version = "5.0.1" }

# Testing
junit                                 = { group = "junit",                            name = "junit",                               version.ref = "junit" }
androidx-junit                        = { group = "androidx.test.ext",                name = "junit",                               version.ref = "junitVersion" }
androidx-espresso-core                = { group = "androidx.test.espresso",           name = "espresso-core",                       version.ref = "espressoCore" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebasePerf" }

[plugins]
android-application  = { id = "com.android.application",              version.ref = "agp" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose",  version.ref = "kotlin" }
google-firebase-firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "googleFirebaseFirebasePerf" }
